# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T17:12:51+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Path, Query

from models import (
    BankAccountDto,
    CashPaymentDto,
    CashReceiptDto,
    CompanyOptionDto,
    CompanySetupConfigViewModel,
    CustomerDto,
    EmailQuoteDto,
    EmailStatementDto,
    FinancialYearDto,
    OwnerOpeningBalanceInPeriodsDto,
    PageResultAccountDto,
    PageResultAnalysisCategoryDto,
    PageResultBankAccountQueryDto,
    PageResultBookTranTypeDto,
    PageResultCashPaymentQueryDto,
    PageResultCashReceiptQueryDto,
    PageResultCategoryTypeDto,
    PageResultCompanySettingDto,
    PageResultCustomerQueryDto,
    PageResultOwnerTypeDto,
    PageResultOwnerTypeGroupDto,
    PageResultPaymentQueryDto,
    PageResultProductDto,
    PageResultPurchaseQueryDto,
    PageResultQuoteDto,
    PageResultSaleRepsDto,
    PageResultSalesCreditNoteQueryDto,
    PageResultSalesEntryQueryDto,
    PageResultSalesInvoiceQueryDto,
    PageResultSalesQueryDto,
    PageResultSupplierQueryDto,
    PageResultUserDefinedFieldDto,
    PageResultVatAnalysisTypeDto,
    PageResultVatCategoryDto,
    PageResultVatRateDto,
    PageResultVatTypeDto,
    PaymentDto,
    ProductDto,
    PurchaseDto,
    QuoteDto,
    QuoteGeneratingInvoiceDto,
    SaleRepsDto,
    SalesEntryDto,
    SalesInvoiceCreditNoteDto,
    SalesInvoiceEmailInfoDto,
    SupplierDto,
    V1BankAccountsBatchPutRequest,
    V1BankAccountsBatchPutResponse,
    V1BankAccountsIdDeleteResponse,
    V1BankAccountsIdPutResponse,
    V1BankAccountsPostResponse,
    V1CashPaymentsBatchPutRequest,
    V1CashPaymentsBatchPutResponse,
    V1CashPaymentsIdDeleteResponse,
    V1CashPaymentsIdPutResponse,
    V1CashPaymentsPostResponse,
    V1CashReceiptsBatchPutRequest,
    V1CashReceiptsBatchPutResponse,
    V1CashReceiptsIdDeleteResponse,
    V1CashReceiptsIdPutResponse,
    V1CashReceiptsPostResponse,
    V1CustomersBatchPutRequest,
    V1CustomersBatchPutResponse,
    V1CustomersIdDeleteResponse,
    V1CustomersIdPutResponse,
    V1CustomersItemIdAccountTransGetResponse,
    V1CustomersItemIdOpeningBalanceListGetResponse,
    V1CustomersItemIdQuotesGetResponse,
    V1CustomersPostResponse,
    V1EmailSendEmailStatementPostResponse,
    V1EmailSendQuotePostResponse,
    V1EmailSendSalesInvoicePostResponse,
    V1PaymentsBatchPutRequest,
    V1PaymentsBatchPutResponse,
    V1PaymentsIdDeleteResponse,
    V1PaymentsIdPutResponse,
    V1PaymentsPostResponse,
    V1ProductsBatchPutRequest,
    V1ProductsBatchPutResponse,
    V1ProductsIdDeleteResponse,
    V1ProductsIdPutResponse,
    V1ProductsPostResponse,
    V1PurchasesBatchPutRequest,
    V1PurchasesBatchPutResponse,
    V1PurchasesIdDeleteResponse,
    V1PurchasesIdPutResponse,
    V1PurchasesPostResponse,
    V1QuotesBatchPutRequest,
    V1QuotesBatchPutResponse,
    V1QuotesCloseIdPutResponse,
    V1QuotesCreateQuoteWithGeneratingReferencePostResponse,
    V1QuotesGenerateSaleInvoicePostResponse,
    V1QuotesIdDeleteResponse,
    V1QuotesIdPutResponse,
    V1QuotesPostResponse,
    V1QuotesReopenIdPutResponse,
    V1SalesCreditNotesBatchPutRequest,
    V1SalesCreditNotesBatchPutResponse,
    V1SalesCreditNotesIdDeleteResponse,
    V1SalesCreditNotesIdPutResponse,
    V1SalesCreditNotesPostResponse,
    V1SalesEntriesBatchPutRequest,
    V1SalesEntriesBatchPutResponse,
    V1SalesEntriesIdDeleteResponse,
    V1SalesEntriesIdPutResponse,
    V1SalesEntriesPostResponse,
    V1SalesInvoicesBatchPutRequest,
    V1SalesInvoicesBatchPutResponse,
    V1SalesInvoicesCreateSaleInvoiceWithGeneratingReferencePostResponse,
    V1SalesInvoicesIdDeleteResponse,
    V1SalesInvoicesIdPutResponse,
    V1SalesInvoicesPostResponse,
    V1SalesRepsBatchPutRequest,
    V1SalesRepsBatchPutResponse,
    V1SalesRepsIdDeleteResponse,
    V1SalesRepsIdPutResponse,
    V1SalesRepsPostResponse,
    V1SuppliersBatchPutRequest,
    V1SuppliersBatchPutResponse,
    V1SuppliersIdDeleteResponse,
    V1SuppliersIdPutResponse,
    V1SuppliersItemIdAccountTransGetResponse,
    V1SuppliersItemIdOpeningBalanceListGetResponse,
    V1SuppliersPostResponse,
    V1VatCategoriesVatRatesPostRequest,
    V1VatCategoriesVatRatesPostResponse,
)

app = MCPProxy(
    description="\r\n<div style='line-height: 30px;'>\r\n    <strong>Welcome to the Big Red Cloud API</strong><br/>\r\n    This API enables programmatic access to Big Red Cloud data.<br/>\r\n    We have used Swagger to auto generate the API documentation on this page, and it also enables direct interaction with the API in this page. <br/>\r\n    To get started, you will require an API Key - check out our guide at <a target='_blank' href='https://www.bigredcloud.com/support/generating-api-key-guide/'>https://www.bigredcloud.com/support/generating-api-key-guide/</a> for information on how to get one. <br/>\r\n    Use the  'Enter API Key' button below to enter your API key and start interacting with your Big Red Cloud data right on this page. <br/>\r\n    The API key will be stored in your browsers local storage for convenience, but you will be able to delete it at any time if you wish. <br/>\r\n    For additional information on the API, check out our support article at <a target='_blank' href='https://www.bigredcloud.com/support/api/'>https://www.bigredcloud.com/support/api/</a><br/>\r\n</div>",
    title='Big Red Cloud API',
    version='v1',
    servers=[{'url': 'https://app.bigredcloud.com/api'}],
)


@app.get('/v1/accounts', tags=['account_management'])
def accounts__get():
    """
        Returns a list of company's Accounts. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" and "code" fields.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/analysisCategories',
    tags=['analysis_category_operations', 'transaction_category_management'],
)
def analysis_categories__get():
    """
        Returns a list of company's Analysis Categories. Supports OData querying protocol.
    Filtering is allowed by "categoryTypeId" field.
    Ordering is allowed by "id" and "orderIndex" fields.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/bankAccounts', tags=['account_management', 'bank_account_operations'])
def bank_accounts__get():
    """
        Returns a list of company's Bank Account. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" and "acCode" fields.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v1/bankAccounts', tags=['account_management', 'bank_account_operations'])
def bank_accounts__post(body: BankAccountDto):
    """
    Creates a new Bank Account.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/bankAccounts/batch', tags=['account_management', 'bank_account_operations']
)
def bank_accounts__process_batch(body: V1BankAccountsBatchPutRequest):
    """
    Processes a batch of Bank Accounts.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/bankAccounts/{id}', tags=['account_management', 'bank_account_operations']
)
def bank_accounts__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Bank Account.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/bankAccounts/{id}', tags=['account_management', 'bank_account_operations']
)
def get_v1_bank_accounts__id(id: int):
    """
    Returns information about a single Bank Account.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/bankAccounts/{id}', tags=['account_management', 'bank_account_operations']
)
def bank_accounts__put(id: int, body: BankAccountDto = ...):
    """
    Updates an existing Bank Account.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/bookTranTypes', tags=['transaction_category_management'])
def book_tran_types__get():
    """
        Returns a list of global Book Transactions' Types. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/cashPayments', tags=['cash_payment_management', 'payment_record_management']
)
def cash_payments__get():
    """
        Returns a list of company's Cash Payments. Supports OData querying protocol.
    Filtering is allowed by "entryDate" field.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/cashPayments', tags=['cash_payment_management', 'payment_record_management']
)
def cash_payments__post(body: CashPaymentDto):
    """
    Creates a new Cash Payment.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/cashPayments/batch',
    tags=[
        'cash_payment_management',
        'payment_record_management',
        'batch_processing_operations',
    ],
)
def cash_payments__process_batch(body: V1CashPaymentsBatchPutRequest):
    """
    Processes a batch of Cash Payments.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/cashPayments/{id}',
    tags=['cash_payment_management', 'payment_record_management'],
)
def cash_payments__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Cash Payment.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/cashPayments/{id}',
    tags=['cash_payment_management', 'payment_record_management'],
)
def get_v1_cash_payments__id(id: int):
    """
    Returns information about a single Cash Payment.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/cashPayments/{id}',
    tags=['cash_payment_management', 'payment_record_management'],
)
def cash_payments__put(id: int, body: CashPaymentDto = ...):
    """
    Updates an existing Cash Payment.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/cashReceipts', tags=['cash_payment_management', 'receipt_processing'])
def cash_receipts__get():
    """
        Returns a list of company's Cash Receipts. Supports OData querying protocol.
    Filtering is allowed by "entryDate" field.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v1/cashReceipts', tags=['cash_payment_management', 'receipt_processing'])
def cash_receipts__post(body: CashReceiptDto):
    """
    Creates a new Cash Receipt.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/cashReceipts/batch',
    tags=[
        'cash_payment_management',
        'receipt_processing',
        'batch_processing_operations',
    ],
)
def cash_receipts__process_batch(body: V1CashReceiptsBatchPutRequest):
    """
    Processes a batch of Cash Receipts.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/cashReceipts/{id}', tags=['cash_payment_management', 'receipt_processing']
)
def cash_receipts__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Cash Receipt.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/cashReceipts/{id}', tags=['cash_payment_management', 'receipt_processing']
)
def get_v1_cash_receipts__id(id: int):
    """
    Returns information about a single Cash Receipt.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/cashReceipts/{id}',
    tags=['receipt_processing', 'cash_payment_management', 'account_management'],
)
def cash_receipts__put(id: int, body: CashReceiptDto = ...):
    """
    Updates an existing Cash Receipt.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/categoryTypes',
    tags=['category_type_operations', 'transaction_category_management'],
)
def category_types__get():
    """
        Returns a list of company's Category Types. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/companySettings', tags=['company_settings_retrieval'])
def company_settings__get():
    """
        Returns a list of company settings. Supports OData querying protocol.
    Filtering is forbidden.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/companySetupConfig', tags=['company_settings_retrieval'])
def company_setup_config__get():
    """
    Returns the company configuration settings.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/companySetupConfig/getCompanyOptions', tags=['company_settings_retrieval']
)
def company_setup_config__get_company_options():
    """
    Returns the company option setting.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/companySetupConfig/getFinancialYear', tags=['company_settings_retrieval'])
def company_setup_config__get_financial_year():
    """
    Returns the financial year.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/customers', tags=['customer_data_management'])
def customers__get():
    """
        Returns a list of company's Customers. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" and "code" fields.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v1/customers', tags=['customer_data_management', 'account_management'])
def customers__post(body: CustomerDto):
    """
    Creates a new Customer.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/customers/batch',
    tags=['customer_data_management', 'batch_processing_operations'],
)
def customers__process_batch(body: V1CustomersBatchPutRequest):
    """
    Processes a batch of Customers.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/customers/{id}', tags=['account_management', 'customer_data_management']
)
def customers__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Customer.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/customers/{id}', tags=['customer_data_management', 'account_management'])
def get_v1_customers__id(
    id: int, need_balance: Optional[bool] = Query(None, alias='needBalance')
):
    """
    Returns information about a single Customer. You may specify that Customer's ledger balance should be calculated.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/v1/customers/{id}', tags=['account_management', 'customer_data_management'])
def customers__put(id: int, body: CustomerDto = ...):
    """
    Updates an existing Customer.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/customers/{itemId}/accountTrans',
    tags=['account_management', 'customer_data_management'],
)
def customers__get_account_trans(item_id: int = Path(..., alias='itemId')):
    """
    Returns a list of Customer's account transactions.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/customers/{itemId}/openingBalance',
    tags=[
        'customer_data_management',
        'account_management',
        'supplier_financial_management',
    ],
)
def customers__get_opening_balance(item_id: int = Path(..., alias='itemId')):
    """
    Returns a Customer's opening balances, calculated for the next periods: current month, one month old, two months old, three and more months old.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/customers/{itemId}/openingBalanceList',
    tags=['customer_data_management', 'bank_account_operations'],
)
def customers__get_opening_balance_list(item_id: int = Path(..., alias='itemId')):
    """
    Returns a list of Customer's opening balance transactions.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/customers/{itemId}/quotes',
    tags=[
        'quote_record_management',
        'customer_data_management',
        'email_notification_services',
    ],
)
def customers__get_quotes(item_id: int = Path(..., alias='itemId')):
    """
    Returns a list of Customer's quotes.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/email/sendEmailStatement',
    tags=['email_notification_services', 'customer_data_management'],
)
def email__send_email_statement(body: EmailStatementDto):
    """
        Sends a Statement email.
    If "toAddress" is not empty then email will be sent to this address. Otherwise email will be sent to Statement Customer's address.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/email/sendQuote',
    tags=['email_notification_services', 'quote_record_management'],
)
def email__send_quote(body: EmailQuoteDto):
    """
        Sends a Quote email.
    If "toAddress" is not empty then email will be sent to this address. Otherwise email will be sent to Statement Customer's address.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/email/sendSalesInvoice',
    tags=['email_notification_services', 'sales_record_management'],
)
def email__send_sales_invoice(body: SalesInvoiceEmailInfoDto):
    """
        Sends a Sales Invoice email.
    If "toAddress" is not empty then email will be sent to this address. Otherwise email will be sent to Sales Invoice Customer's address.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/ownerTypeGroups', tags=['owner_type_operations', 'company_settings_retrieval']
)
def owner_type_groups__get():
    """
        Returns a list of global Owner Type Groups. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/ownerTypes', tags=['owner_type_operations', 'transaction_category_management']
)
def owner_types__get():
    """
        Returns a list of global Owner Types. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/payments', tags=['payment_record_management', 'cash_payment_management'])
def payments__get():
    """
        Returns a list of company's Payments. Supports OData querying protocol.
    Filtering is allowed by "entryDate" field.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v1/payments', tags=['payment_record_management', 'cash_payment_management'])
def payments__post(body: PaymentDto):
    """
    Creates a new Payment.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/payments/batch',
    tags=[
        'payment_record_management',
        'batch_processing_operations',
        'cash_payment_management',
    ],
)
def payments__process_batch(body: V1PaymentsBatchPutRequest):
    """
    Processes a batch of Payments.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/payments/{id}', tags=['payment_record_management', 'cash_payment_management']
)
def payments__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Payment.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/payments/{id}', tags=['payment_record_management', 'cash_payment_management']
)
def get_v1_payments__id(id: int):
    """
    Returns information about a single Payments.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/payments/{id}', tags=['payment_record_management', 'cash_payment_management']
)
def payments__put(id: int, body: PaymentDto = ...):
    """
    Updates an existing Payment.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/productTypes',
    tags=['transaction_category_management', 'category_type_operations'],
)
def product_types__get():
    """
        Returns a list of global Product Types. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/products', tags=['product_inventory_management'])
def products__get():
    """
        Returns a list of company's Products. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" and "stockCode" fields.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v1/products', tags=['product_inventory_management'])
def products__post(body: ProductDto):
    """
    Creates a new Product.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/products/batch',
    tags=['product_inventory_management', 'batch_processing_operations'],
)
def products__process_batch(body: V1ProductsBatchPutRequest):
    """
    Processes a batch of Products.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/v1/products/{id}', tags=['product_inventory_management'])
def products__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Product.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/products/{id}', tags=['product_inventory_management'])
def get_v1_products__id(id: int):
    """
    Returns information about a single Product.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/v1/products/{id}', tags=['product_inventory_management'])
def products__put(id: int, body: ProductDto = ...):
    """
    Updates an existing Product.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/purchases', tags=['purchase_record_management', 'account_management'])
def purchases__get():
    """
        Returns a list of company's Purchases. Supports OData querying protocol.
    Filtering is allowed by "entryDate" field.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v1/purchases', tags=['purchase_record_management', 'account_management'])
def purchases__post(body: PurchaseDto):
    """
    Creates a new Purchase.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/purchases/batch',
    tags=['purchase_record_management', 'batch_processing_operations'],
)
def purchases__process_batch(body: V1PurchasesBatchPutRequest):
    """
    Processes a batch of Purchases.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/v1/purchases/{id}', tags=['purchase_record_management'])
def purchases__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Purchase.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/purchases/{id}', tags=['purchase_record_management'])
def get_v1_purchases__id(id: int):
    """
    Returns information about a single Purchases.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/v1/purchases/{id}', tags=['purchase_record_management'])
def purchases__put(id: int, body: PurchaseDto = ...):
    """
    Updates an existing Purchase.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/quotes', tags=['quote_record_management', 'email_notification_services'])
def quote__get():
    """
        Returns a list of company's Quotes.
    Filtering is forbidden.
    Ordering is allowed by "id".
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v1/quotes', tags=['quote_record_management', 'email_notification_services'])
def quote__post(body: QuoteDto):
    """
    Creates a new Quote.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/quotes/batch', tags=['quote_record_management', 'batch_processing_operations']
)
def quote__process_batch(body: V1QuotesBatchPutRequest):
    """
    Processes a batch of Quote.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/v1/quotes/close/{id}', tags=['quote_record_management'])
def quote__close(id: int):
    """
    Close a Quote.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/quotes/createQuoteWithGeneratingReference',
    tags=['quote_record_management', 'email_notification_services'],
)
def quote__post__create_quote_with_generating_reference(body: QuoteDto):
    """
    Creates a new Quote with auto generating reference.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/quotes/generateSaleInvoice',
    tags=[
        'quote_record_management',
        'sales_record_management',
        'batch_processing_operations',
    ],
)
def quote__post__generate_sale_invoice(body: QuoteGeneratingInvoiceDto):
    """
        Generate a sale invoice from a Quote.
    When sale invoice is empty, new sale invoice will be generated from Quote.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/v1/quotes/reopen/{id}', tags=['quote_record_management'])
def quote__reopen(id: int):
    """
    Reopen a Quote.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/v1/quotes/{id}', tags=['quote_record_management'])
def quote__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Quote.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/quotes/{id}', tags=['quote_record_management', 'email_notification_services']
)
def get_v1_quotes__id(id: int):
    """
    Returns information about a single Quote.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/quotes/{id}', tags=['quote_record_management', 'email_notification_services']
)
def quote__put(id: int, body: QuoteDto = ...):
    """
    Updates an existing Quote.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/sales', tags=['sales_record_management', 'account_management'])
def sales__get():
    """
        Returns a list of company's Sales Entries, Sales Invoices and Sales Credit Notes. Supports OData querying protocol.
    Filtering is allowed by "entryDate" field.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/salesCreditNotes',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def sales_credit_notes__get():
    """
        Returns a list of company's Sales Credit Notes. Supports OData querying protocol.
    Filtering is allowed by "entryDate" field.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/salesCreditNotes',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def sales_credit_notes__post(body: SalesInvoiceCreditNoteDto):
    """
    Creates a new Sales Credit Note.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/salesCreditNotes/batch',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def sales_credit_notes__process_batch(body: V1SalesCreditNotesBatchPutRequest):
    """
    Processes a batch of Sales Credit Notes.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/salesCreditNotes/{id}',
    tags=[
        'sales_record_management',
        'payment_record_management',
        'batch_processing_operations',
    ],
)
def sales_credit_notes__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Sales Credit Note.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/salesCreditNotes/{id}',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def get_v1_sales_credit_notes__id(id: int):
    """
    Returns information about a single Sales Credit Note.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/salesCreditNotes/{id}',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def sales_credit_notes__put(id: int, body: SalesInvoiceCreditNoteDto = ...):
    """
    Updates an existing Sales Credit Note.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/salesEntries', tags=['sales_record_management', 'batch_processing_operations']
)
def sales_entries__get():
    """
        Returns a list of company's Sales Entries. Supports OData querying protocol.
    Filtering is allowed by "entryDate" field.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/salesEntries', tags=['sales_record_management', 'batch_processing_operations']
)
def sales_entries__post(body: SalesEntryDto):
    """
    Creates a new Sales Entry.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/salesEntries/batch',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def sales_entries__process_batch(body: V1SalesEntriesBatchPutRequest):
    """
    Processes a batch of Sales Entries.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/salesEntries/{id}',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def sales_entries__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Sales Entry.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/salesEntries/{id}',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def get_v1_sales_entries__id(id: int):
    """
    Returns information about a single Sales Entry.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/salesEntries/{id}',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def sales_entries__put(id: int, body: SalesEntryDto = ...):
    """
    Updates an existing Sales Entry.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/salesInvoices', tags=['sales_record_management', 'batch_processing_operations']
)
def sales_invoices__get():
    """
        Returns a list of company's Sales Invoices. Supports OData querying protocol.
    Filtering is allowed by "entryDate" field.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/salesInvoices', tags=['sales_record_management', 'batch_processing_operations']
)
def sales_invoices__post(body: SalesInvoiceCreditNoteDto):
    """
    Creates a new Sales Invoice.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/salesInvoices/batch',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def sales_invoices__process_batch(body: V1SalesInvoicesBatchPutRequest):
    """
    Processes a batch of Sales Invoices.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/salesInvoices/createSaleInvoiceWithGeneratingReference',
    tags=[
        'sales_record_management',
        'batch_processing_operations',
        'account_management',
    ],
)
def create_sale_invoice_with_auto_reference(body: SalesInvoiceCreditNoteDto):
    """
    Creates a new Sale Invoice with auto generating reference.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/salesInvoices/{id}',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def sales_invoices__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Sales Invoice.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/salesInvoices/{id}',
    tags=[
        'sales_record_management',
        'account_management',
        'batch_processing_operations',
    ],
)
def get_v1_sales_invoices__id(id: int):
    """
    Returns information about a single Sales Invoice.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/salesInvoices/{id}',
    tags=['sales_record_management', 'batch_processing_operations'],
)
def sales_invoices__put(id: int, body: SalesInvoiceCreditNoteDto = ...):
    """
    Updates an existing Sales Invoice.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/salesReps', tags=['sales_rep_operations'])
def sales_rep__get():
    """
        Returns a list of company's SaleRep.
    Filtering is forbidden.
    Ordering is allowed by "id".
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v1/salesReps', tags=['sales_rep_operations', 'account_management'])
def sales_rep__post(body: SaleRepsDto):
    """
    Creates a new SaleRep.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/salesReps/batch', tags=['sales_rep_operations', 'batch_processing_operations']
)
def sales_rep__process_batch(body: V1SalesRepsBatchPutRequest):
    """
    Processes a batch of Sale Rep.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/v1/salesReps/{id}', tags=['sales_rep_operations', 'account_management'])
def sales_rep__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Sale Rep.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/salesReps/{id}', tags=['sales_rep_operations', 'customer_data_management']
)
def get_v1_sales_reps__id(id: int):
    """
    Returns information about a single SaleRep.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/v1/salesReps/{id}', tags=['sales_rep_operations', 'account_management'])
def sales_rep__put(id: int, body: SaleRepsDto = ...):
    """
    Updates an existing Sale Rep.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/suppliers', tags=['supplier_data_management'])
def suppliers__get():
    """
        Returns a list of company's Suppliers. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" and "code" fields.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v1/suppliers', tags=['supplier_data_management'])
def suppliers__post(body: SupplierDto):
    """
    Creates a new Supplier.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v1/suppliers/batch',
    tags=['supplier_data_management', 'batch_processing_operations'],
)
def suppliers__process_batch(body: V1SuppliersBatchPutRequest):
    """
    Processes a batch of Suppliers.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/v1/suppliers/{id}', tags=['supplier_data_management'])
def suppliers__delete(id: int, timestamp: str = ...):
    """
    Removes an existing Supplier.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/suppliers/{id}',
    tags=['supplier_data_management', 'supplier_financial_management'],
)
def get_v1_suppliers__id(
    id: int, need_balance: Optional[bool] = Query(None, alias='needBalance')
):
    """
    Returns information about a single Supplier. You may specify that Supplier's ledger balance should be calculated.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/v1/suppliers/{id}', tags=['supplier_data_management'])
def suppliers__put(id: int, body: SupplierDto = ...):
    """
    Updates an existing Supplier.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/suppliers/{itemId}/accountTrans',
    tags=['supplier_data_management', 'supplier_financial_management'],
)
def suppliers__get_account_trans(item_id: int = Path(..., alias='itemId')):
    """
    Returns a list of Supplier's account transactions.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/suppliers/{itemId}/openingBalance',
    tags=['supplier_financial_management', 'supplier_data_management'],
)
def suppliers__get_opening_balance(item_id: int = Path(..., alias='itemId')):
    """
    Returns a Supplier's opening balances, calculated for the next periods: current month, one month old, two months old, three and more months old.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/suppliers/{itemId}/openingBalanceList',
    tags=['supplier_financial_management', 'supplier_data_management'],
)
def suppliers__get_opening_balance_list(item_id: int = Path(..., alias='itemId')):
    """
    Returns a list of Supplier's opening balance transactions.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/userDefinedFields',
    tags=[
        'user_defined_fields_operations',
        'analysis_category_operations',
        'category_type_operations',
    ],
)
def user_defined_fields__get():
    """
        Returns a list of company's User Defined Fields. Supports OData querying protocol.
    Filtering is allowed by "categoryTypeId" field.
    Ordering is allowed by "id" and "orderIndex" fields.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/vatAnalysisTypes',
    tags=['vat_analysis_operations', 'transaction_category_management'],
)
def vat_analysis_types__get():
    """
        Returns a list of global Vat Analysis Types. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/vatCategories',
    tags=['vat_reporting_and_management', 'vat_analysis_operations'],
)
def vat_categories__get():
    """
        Returns a list of global Vat Categories. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/vatCategories/vatRates',
    tags=['vat_reporting_and_management', 'vat_analysis_operations'],
)
def vat_categories__process_vat_rates(body: V1VatCategoriesVatRatesPostRequest):
    """
    Process Vat Rates
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/vatRates', tags=['vat_reporting_and_management'])
def vat_rates__get():
    """
        Returns a list of company's Vat Rates. Supports OData querying protocol.
    Filtering is allowed by "vatCategoryId" field.
    Ordering is allowed by "id" and "orderIndex" fields.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/vatTypes', tags=['vat_reporting_and_management', 'vat_analysis_operations']
)
def vat_types__get():
    """
        Returns a list of global Vat Types. Supports OData querying protocol.
    Filtering is forbidden.
    Ordering is allowed by "id" field.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
