# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T17:12:51+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class AcEntryDto(BaseModel):
    accountCode: Optional[str] = None
    analysisCategoryId: Optional[int] = None
    description: Optional[str] = None
    id: Optional[int] = None
    value: Optional[float] = None


class AccountDto(BaseModel):
    accountGroup: Optional[str] = None
    accountType: Optional[str] = None
    code: Optional[str] = None
    description: Optional[str] = None
    id: Optional[int] = None


class AccountTranDto(BaseModel):
    bookTranId: Optional[int] = None
    bookTranTypeId: Optional[int] = None
    bookTransactionReference: Optional[str] = None
    bookTypeDesc: Optional[str] = None
    credit: Optional[float] = None
    debit: Optional[float] = None
    id: Optional[int] = None
    procDate: Optional[datetime] = None


class AcudfValueDto(BaseModel):
    description: Optional[str] = None
    id: Optional[int] = None
    userDefinedFieldId: Optional[int] = None
    value: Optional[str] = None


class AnalysisCategoryDto(BaseModel):
    accountCode: Optional[str] = None
    accountId: Optional[int] = None
    categoryTypeId: Optional[int] = None
    description: Optional[str] = None
    id: Optional[int] = None
    orderIndex: Optional[int] = None


class BankAccountDto(BaseModel):
    acCode: Optional[str] = None
    accountName: Optional[str] = None
    accountNumber: Optional[str] = None
    address: Optional[List[str]] = None
    bankFeedSource: Optional[int] = None
    businessIdentifierCodes: Optional[str] = None
    categoryId: Optional[int] = None
    creditorScheme: Optional[str] = None
    details: Optional[str] = None
    id: Optional[int] = None
    internationalBankAccountNumber: Optional[str] = None
    isDefaultBank: Optional[bool] = None
    lastChq: Optional[str] = None
    nominalAcCode: Optional[str] = None
    oBalance: Optional[float] = None
    sortCode: Optional[str] = None
    timestamp: Optional[str] = None


class BankAccountQueryDto(BaseModel):
    acCode: Optional[str] = None
    accountName: Optional[str] = None
    accountNumber: Optional[str] = None
    address: Optional[List[str]] = None
    bankFeedSource: Optional[int] = None
    businessIdentifierCodes: Optional[str] = None
    categoryId: Optional[int] = None
    creditorScheme: Optional[str] = None
    details: Optional[str] = None
    id: Optional[int] = None
    internationalBankAccountNumber: Optional[str] = None
    isDefaultBank: Optional[bool] = None
    lastChq: Optional[str] = None
    nominalAcCode: Optional[str] = None
    sortCode: Optional[str] = None
    timestamp: Optional[str] = None


class OpCode(Enum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class BatchItemBankAccountDto(BaseModel):
    item: Optional[BankAccountDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class BookTranTypeDto(BaseModel):
    code: Optional[str] = None
    description: Optional[str] = None
    id: Optional[int] = None


class CashPaymentDto(BaseModel):
    acCode: Optional[str] = None
    acEntries: Optional[List[AcEntryDto]] = None
    bankAccountCode: Optional[str] = None
    bankAccountId: Optional[int] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    detailCollection: Optional[List[str]] = None
    discount: Optional[float] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    ledger: Optional[float] = None
    lodgement: Optional[float] = None
    note: Optional[str] = None
    plaidTransactionId: Optional[str] = None
    procDate: Optional[datetime] = None
    supplierId: Optional[int] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None


class CashPaymentQueryDto(BaseModel):
    acCode: Optional[str] = None
    acEntries: Optional[List[AcEntryDto]] = None
    bankAccountCode: Optional[str] = None
    bankAccountId: Optional[int] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    detailCollection: Optional[List[str]] = None
    discount: Optional[float] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    ledger: Optional[float] = None
    lodgement: Optional[float] = None
    note: Optional[str] = None
    plaidTransactionId: Optional[str] = None
    procDate: Optional[datetime] = None
    supplierId: Optional[int] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    unallocated: Optional[float] = None


class CategoryTypeDto(BaseModel):
    description: Optional[str] = None
    id: Optional[int] = None


class CompanyFinancialYearViewModel(BaseModel):
    firstMonth: Optional[int] = None
    startMonth: Optional[int] = None
    startYear: Optional[int] = None


class CompanyGeneralDetaisViewModel(BaseModel):
    companyAddresses: Optional[List[str]] = None
    companyName: Optional[str] = None
    currencyCode: Optional[str] = None
    currencyDescription: Optional[str] = None
    currencyId: Optional[int] = None
    currentcySymbol: Optional[str] = None
    emails: Optional[List[str]] = None
    faxes: Optional[List[str]] = None
    phones: Optional[List[str]] = None
    regionDescription: Optional[str] = None
    regionId: Optional[int] = None
    vatReg: Optional[str] = None


class CompanyOptionDto(BaseModel):
    allowEntryOfGrossPriceInInvoicing: Optional[bool] = None
    creditInputForReverseChargeVAT: Optional[bool] = None
    creditNoteJournalAgeingName: Optional[str] = None
    creditNoteJournalAgeingValue: Optional[int] = None
    discrepancyAllowed: Optional[float] = None
    enableVOCRReporting: Optional[bool] = None
    marginVatScheme: Optional[bool] = None
    printOSItemsOnly: Optional[bool] = None
    purchasesVatAnalysisType: Optional[int] = None
    salesVatAnalysisType: Optional[int] = None
    useAllocations: Optional[bool] = None
    useNominal: Optional[bool] = None
    useNominalCode: Optional[bool] = None
    vocrSettingValue: Optional[bool] = None


class CompanyOptionViewModel(BaseModel):
    allowEntryOfGrossPriceInInvoicing: Optional[bool] = None
    creditInputForReverseChargeVAT: Optional[bool] = None
    creditNoteJournalAgeingName: Optional[str] = None
    creditNoteJournalAgeingValue: Optional[int] = None
    discrepancyAllowed: Optional[float] = None
    enableVOCRReporting: Optional[bool] = None
    marginVatScheme: Optional[bool] = None
    printOSItemsOnly: Optional[bool] = None
    purchasesVatAnalysisType: Optional[int] = None
    salesVatAnalysisType: Optional[int] = None
    useAllocations: Optional[bool] = None
    useNominal: Optional[bool] = None
    useNominalCode: Optional[bool] = None
    vocrSettingValue: Optional[bool] = None


class CompanyReferenceSettingViewModel(BaseModel):
    creditorsJournal: Optional[bool] = None
    debtorsJournal: Optional[bool] = None
    purchases: Optional[bool] = None
    sales: Optional[bool] = None


class CompanySettingDto(BaseModel):
    enableVOCRReporting: Optional[bool] = None
    id: Optional[int] = None
    useAllocations: Optional[bool] = None
    value: Optional[str] = None
    vocrSettingValue: Optional[bool] = None


class CompanySetupConfigViewModel(BaseModel):
    financialYear: Optional[CompanyFinancialYearViewModel] = None
    generalDetails: Optional[CompanyGeneralDetaisViewModel] = None
    options: Optional[CompanyOptionViewModel] = None
    referenceSettings: Optional[CompanyReferenceSettingViewModel] = None


class EFTBankDto(BaseModel):
    branch: Optional[str] = None
    id: Optional[int] = None
    name: Optional[str] = None
    sortCode: Optional[str] = None


class EmailQuoteDto(BaseModel):
    bccAddresses: Optional[List[str]] = None
    messageBody: Optional[str] = None
    quoteId: Optional[int] = None
    toAddress: Optional[str] = None


class EmailStatementDto(BaseModel):
    bccAddresses: Optional[List[str]] = None
    customerId: Optional[int] = None
    fromPeriod: Optional[datetime] = None
    messageBody: Optional[str] = None
    minimumBalance: Optional[float] = None
    toAddress: Optional[str] = None
    toPeriod: Optional[datetime] = None


class FilterQueryValidator(BaseModel):
    pass


class FinancialYearDto(BaseModel):
    firstMonth: Optional[int] = None
    startMonth: Optional[int] = None
    startYear: Optional[int] = None


class IEdmDirectValueAnnotationsManager(BaseModel):
    pass


class SchemaElementKind(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4


class IEdmSchemaElement(BaseModel):
    Name: Optional[str] = None
    Namespace: Optional[str] = None
    SchemaElementKind_1: Optional[SchemaElementKind] = Field(
        None, alias='SchemaElementKind'
    )


class TermKind(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2


class IEdmTerm(BaseModel):
    Name: Optional[str] = None
    Namespace: Optional[str] = None
    SchemaElementKind_1: Optional[SchemaElementKind] = Field(
        None, alias='SchemaElementKind'
    )
    TermKind_1: Optional[TermKind] = Field(None, alias='TermKind')


class TypeKind(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7


class IEdmType(BaseModel):
    TypeKind_1: Optional[TypeKind] = Field(None, alias='TypeKind')


class IEdmTypeReference(BaseModel):
    Definition: Optional[IEdmType] = None
    IsNullable: Optional[bool] = None


class IEdmVocabularyAnnotatable(BaseModel):
    pass


class IEdmVocabularyAnnotation(BaseModel):
    Qualifier: Optional[str] = None
    Target: Optional[IEdmVocabularyAnnotatable] = None
    Term: Optional[IEdmTerm] = None


class Value(Enum):
    integer_0 = 0
    integer_1 = 1


class ODataQueryValidator(BaseModel):
    pass


class ODataRawQueryOptions(BaseModel):
    Expand: Optional[str] = None
    Filter: Optional[str] = None
    Format: Optional[str] = None
    InlineCount: Optional[str] = None
    OrderBy: Optional[str] = None
    Select: Optional[str] = None
    Skip: Optional[str] = None
    SkipToken: Optional[str] = None
    Top: Optional[str] = None


class Direction(Enum):
    integer_0 = 0
    integer_1 = 1


class OrderByNode(BaseModel):
    Direction_1: Optional[Direction] = Field(None, alias='Direction')


class OrderByQueryValidator(BaseModel):
    pass


class OwnerOpeningBalanceInPeriodsDto(BaseModel):
    currentMonth: Optional[float] = None
    oneMonthOld: Optional[float] = None
    threeMonthsOld: Optional[float] = None
    twoMonthsOld: Optional[float] = None


class OwnerOpeningBalanceVatEntryDto(BaseModel):
    amount: Optional[float] = None
    vatRateId: Optional[int] = None


class OwnerTypeDto(BaseModel):
    description: Optional[str] = None
    id: Optional[int] = None
    recordTypeGroupId: Optional[int] = None


class OwnerTypeGroupDto(BaseModel):
    description: Optional[str] = None
    id: Optional[int] = None


class PageResultAccountDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[AccountDto]] = None
    NextPageLink: Optional[str] = None


class PageResultAnalysisCategoryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[AnalysisCategoryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultBankAccountQueryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[BankAccountQueryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultBookTranTypeDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[BookTranTypeDto]] = None
    NextPageLink: Optional[str] = None


class PageResultCashPaymentQueryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[CashPaymentQueryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultCategoryTypeDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[CategoryTypeDto]] = None
    NextPageLink: Optional[str] = None


class PageResultCompanySettingDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[CompanySettingDto]] = None
    NextPageLink: Optional[str] = None


class PageResultOwnerTypeDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[OwnerTypeDto]] = None
    NextPageLink: Optional[str] = None


class PageResultOwnerTypeGroupDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[OwnerTypeGroupDto]] = None
    NextPageLink: Optional[str] = None


class PaymentDto(BaseModel):
    acCode: Optional[str] = None
    acEntries: Optional[List[AcEntryDto]] = None
    bankAccountCode: Optional[str] = None
    bankAccountId: Optional[int] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    detailCollection: Optional[List[str]] = None
    discount: Optional[float] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    note: Optional[str] = None
    plaidTransactionId: Optional[str] = None
    procDate: Optional[datetime] = None
    reference: Optional[str] = None
    supplierId: Optional[int] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    transferBankCode: Optional[str] = None
    transferBankId: Optional[int] = None
    unallocated: Optional[float] = None


class PaymentQueryDto(BaseModel):
    acCode: Optional[str] = None
    acEntries: Optional[List[AcEntryDto]] = None
    bankAccountCode: Optional[str] = None
    bankAccountId: Optional[int] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    detailCollection: Optional[List[str]] = None
    discount: Optional[float] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    note: Optional[str] = None
    plaidTransactionId: Optional[str] = None
    procDate: Optional[datetime] = None
    reference: Optional[str] = None
    supplierId: Optional[int] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    transferBankCode: Optional[str] = None
    transferBankId: Optional[int] = None
    unallocated: Optional[float] = None


class ProductDto(BaseModel):
    details: Optional[List[str]] = None
    grossUnitPrice: Optional[bool] = None
    hasDefaultVatRate: Optional[bool] = None
    id: Optional[int] = None
    productTypeId: Optional[int] = None
    stockCode: Optional[str] = None
    timestamp: Optional[str] = None
    unitPrice: Optional[float] = None
    vatAnalysisTypeId: Optional[int] = None
    vatRateId: Optional[int] = None


class ProductTranDto(BaseModel):
    acEntries: Optional[List[AcEntryDto]] = None
    amount: Optional[float] = None
    amountNet: float
    id: Optional[int] = None
    percentage: Optional[float] = None
    productCode: Optional[str] = None
    productId: Optional[int] = None
    quantity: Optional[float] = None
    tranNotes: Optional[List[str]] = None
    unitPrice: Optional[float] = None
    vat: Optional[float] = None
    vatAnalysisTypeId: Optional[int] = None
    vatRateId: Optional[int] = None


class ProductTranQueryDto(BaseModel):
    acEntries: Optional[List[AcEntryDto]] = None
    amount: Optional[float] = None
    amountNet: Optional[float] = None
    id: Optional[int] = None
    percentage: Optional[float] = None
    productCode: Optional[str] = None
    productId: Optional[int] = None
    quantity: Optional[float] = None
    tranNotes: Optional[List[str]] = None
    unitPrice: Optional[float] = None
    vat: Optional[float] = None
    vatAnalysisTypeId: Optional[int] = None
    vatRateId: Optional[int] = None


class QuoteAcEntriesDto(BaseModel):
    accountCode: Optional[str] = None
    analysisCategoryId: Optional[int] = None
    companyId: Optional[int] = None
    id: Optional[int] = None
    quoteProductTranId: Optional[int] = None
    value: Optional[float] = None


class QuoteProductTransDto(BaseModel):
    acEntries: Optional[List[QuoteAcEntriesDto]] = None
    amount: Optional[float] = None
    companyId: Optional[int] = None
    id: Optional[int] = None
    percentage: Optional[float] = None
    productCode: Optional[str] = None
    productId: Optional[int] = None
    quantity: Optional[float] = None
    tranNotes: Optional[List[str]] = None
    unitPrice: Optional[float] = None
    vatAmount: Optional[float] = None
    vatAnalysisTypeId: Optional[int] = None
    vatRateId: Optional[int] = None


class RangeVariable(BaseModel):
    Kind: Optional[int] = None
    Name: Optional[str] = None
    TypeReference: Optional[IEdmTypeReference] = None


class SaleRepsDto(BaseModel):
    code: Optional[str] = None
    companyId: Optional[int] = None
    email: Optional[str] = None
    id: Optional[int] = None
    name: Optional[str] = None
    phone: Optional[str] = None
    timeStamp: Optional[str] = None


class SalesCreditNoteQueryDto(BaseModel):
    acCode: Optional[str] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    customerId: Optional[int] = None
    deliveryTo: Optional[List[str]] = None
    details: Optional[str] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    loType: Optional[str] = None
    netGoods: Optional[float] = None
    netServices: Optional[float] = None
    note: Optional[str] = None
    ourReference: Optional[str] = None
    procDate: Optional[datetime] = None
    productTrans: Optional[List[ProductTranQueryDto]] = None
    quoteId: Optional[int] = None
    reference: Optional[str] = None
    saleRepCode: Optional[str] = None
    saleRepId: Optional[int] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    totalNet: Optional[float] = None
    totalVAT: Optional[float] = None
    unpaid: Optional[float] = None
    vatTypeId: Optional[int] = None
    yourReference: Optional[str] = None


class SalesInvoiceCreditNoteDto(BaseModel):
    acCode: Optional[str] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    customerId: Optional[int] = None
    deliveryTo: Optional[List[str]] = None
    details: Optional[str] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    loType: Optional[str] = None
    netGoods: Optional[float] = None
    netServices: Optional[float] = None
    note: Optional[str] = None
    ourReference: Optional[str] = None
    procDate: Optional[datetime] = None
    productTrans: Optional[List[ProductTranDto]] = None
    quoteId: Optional[int] = None
    reference: Optional[str] = None
    saleRepCode: Optional[str] = None
    saleRepId: Optional[int] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    totalNet: Optional[float] = None
    totalVAT: Optional[float] = None
    unpaid: Optional[float] = None
    vatTypeId: Optional[int] = None
    yourReference: Optional[str] = None


class SalesInvoiceEmailInfoDto(BaseModel):
    bccAddresses: Optional[List[str]] = None
    messageBody: Optional[str] = None
    salesInvoiceId: Optional[int] = None
    toAddress: Optional[str] = None


class SalesInvoiceQueryDto(BaseModel):
    acCode: Optional[str] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    customerId: Optional[int] = None
    deliveryTo: Optional[List[str]] = None
    details: Optional[str] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    loType: Optional[str] = None
    netGoods: Optional[float] = None
    netServices: Optional[float] = None
    note: Optional[str] = None
    ourReference: Optional[str] = None
    procDate: Optional[datetime] = None
    productTrans: Optional[List[ProductTranQueryDto]] = None
    quoteId: Optional[int] = None
    reference: Optional[str] = None
    saleRepCode: Optional[str] = None
    saleRepId: Optional[int] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    totalNet: Optional[float] = None
    totalVAT: Optional[float] = None
    unpaid: Optional[float] = None
    vatTypeId: Optional[int] = None
    yourReference: Optional[str] = None


class SelectExpandQueryValidator(BaseModel):
    pass


class SelectItem(BaseModel):
    pass


class Kind(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7
    integer_8 = 8
    integer_9 = 9
    integer_10 = 10
    integer_11 = 11
    integer_12 = 12
    integer_13 = 13
    integer_14 = 14
    integer_15 = 15
    integer_16 = 16
    integer_17 = 17
    integer_18 = 18
    integer_19 = 19
    integer_20 = 20


class SingleValueNode(BaseModel):
    Kind_1: Optional[Kind] = Field(None, alias='Kind')
    TypeReference: Optional[IEdmTypeReference] = None


class SkipQueryValidator(BaseModel):
    pass


class SupplierQueryDto(BaseModel):
    accountName: Optional[str] = None
    accountNumber: Optional[str] = None
    additionalEmails: Optional[List[str]] = None
    address: Optional[List[str]] = None
    authCode: Optional[str] = None
    bank: Optional[EFTBankDto] = None
    businessIdentifierCode: Optional[str] = None
    code: Optional[str] = None
    contact: Optional[str] = None
    eFTReference: Optional[str] = None
    email: Optional[str] = None
    fax: Optional[str] = None
    id: Optional[int] = None
    internationalBankAccountNumber: Optional[str] = None
    mobile: Optional[str] = None
    name: Optional[str] = None
    ourCode: Optional[str] = None
    ownerTypeId: Optional[int] = None
    phone: Optional[str] = None
    postponedAccounting: Optional[bool] = None
    timestamp: Optional[str] = None
    vatAnalysisTypeId: Optional[int] = None
    vatReg: Optional[str] = None
    vatType: Optional[int] = None


class TopQueryValidator(BaseModel):
    pass


class UserDefinedFieldDto(BaseModel):
    categoryTypeId: Optional[int] = None
    description: Optional[str] = None
    id: Optional[int] = None
    orderIndex: Optional[int] = None


class VatAnalysisTypeDto(BaseModel):
    description: Optional[str] = None
    id: Optional[int] = None


class VatCategoryDto(BaseModel):
    description: Optional[str] = None
    id: Optional[int] = None


class VatEntryDto(BaseModel):
    amount: Optional[float] = None
    id: Optional[int] = None
    percentage: Optional[float] = None
    vatRateId: Optional[int] = None


class VatRateDto(BaseModel):
    id: Optional[int] = None
    isActive: Optional[bool] = None
    isDefault: Optional[bool] = None
    orderIndex: Optional[int] = None
    percentage: Optional[float] = None
    timestamp: Optional[str] = None
    vatCategoryId: Optional[int] = None


class VatRatesByVatCategoryDto(BaseModel):
    vatCategoryId: Optional[int] = None
    vatRates: Optional[List[VatRateDto]] = None


class VatTypeDto(BaseModel):
    code: Optional[str] = None
    description: Optional[str] = None
    id: Optional[int] = None
    isNotApplicable: Optional[bool] = None
    isOnlyZero: Optional[bool] = None


class V1BankAccountsPostResponse(BaseModel):
    pass


class V1BankAccountsBatchPutRequest(RootModel[List[BatchItemBankAccountDto]]):
    root: List[BatchItemBankAccountDto]


class V1BankAccountsBatchPutResponse(BaseModel):
    pass


class V1BankAccountsIdDeleteResponse(BaseModel):
    pass


class V1BankAccountsIdPutResponse(BaseModel):
    pass


class V1CashPaymentsPostResponse(BaseModel):
    pass


class V1CashPaymentsBatchPutResponse(BaseModel):
    pass


class V1CashPaymentsIdDeleteResponse(BaseModel):
    pass


class V1CashPaymentsIdPutResponse(BaseModel):
    pass


class V1CashReceiptsPostResponse(BaseModel):
    pass


class V1CashReceiptsBatchPutResponse(BaseModel):
    pass


class V1CashReceiptsIdDeleteResponse(BaseModel):
    pass


class V1CashReceiptsIdPutResponse(BaseModel):
    pass


class V1CustomersPostResponse(BaseModel):
    pass


class V1CustomersBatchPutResponse(BaseModel):
    pass


class V1CustomersIdDeleteResponse(BaseModel):
    pass


class V1CustomersIdPutResponse(BaseModel):
    pass


class V1CustomersItemIdAccountTransGetResponse(RootModel[List[AccountTranDto]]):
    root: List[AccountTranDto]


class V1EmailSendEmailStatementPostResponse(BaseModel):
    pass


class V1EmailSendQuotePostResponse(BaseModel):
    pass


class V1EmailSendSalesInvoicePostResponse(BaseModel):
    pass


class V1PaymentsPostResponse(BaseModel):
    pass


class V1PaymentsBatchPutResponse(BaseModel):
    pass


class V1PaymentsIdDeleteResponse(BaseModel):
    pass


class V1PaymentsIdPutResponse(BaseModel):
    pass


class V1ProductsPostResponse(BaseModel):
    pass


class V1ProductsBatchPutResponse(BaseModel):
    pass


class V1ProductsIdDeleteResponse(BaseModel):
    pass


class V1ProductsIdPutResponse(BaseModel):
    pass


class V1PurchasesPostResponse(BaseModel):
    pass


class V1PurchasesBatchPutResponse(BaseModel):
    pass


class V1PurchasesIdDeleteResponse(BaseModel):
    pass


class V1PurchasesIdPutResponse(BaseModel):
    pass


class V1QuotesPostResponse(BaseModel):
    pass


class V1QuotesBatchPutResponse(BaseModel):
    pass


class V1QuotesCloseIdPutResponse(BaseModel):
    pass


class V1QuotesCreateQuoteWithGeneratingReferencePostResponse(BaseModel):
    pass


class V1QuotesGenerateSaleInvoicePostResponse(BaseModel):
    pass


class V1QuotesReopenIdPutResponse(BaseModel):
    pass


class V1QuotesIdDeleteResponse(BaseModel):
    pass


class V1QuotesIdPutResponse(BaseModel):
    pass


class V1SalesCreditNotesPostResponse(BaseModel):
    pass


class V1SalesCreditNotesBatchPutResponse(BaseModel):
    pass


class V1SalesCreditNotesIdDeleteResponse(BaseModel):
    pass


class V1SalesCreditNotesIdPutResponse(BaseModel):
    pass


class V1SalesEntriesPostResponse(BaseModel):
    pass


class V1SalesEntriesBatchPutResponse(BaseModel):
    pass


class V1SalesEntriesIdDeleteResponse(BaseModel):
    pass


class V1SalesEntriesIdPutResponse(BaseModel):
    pass


class V1SalesInvoicesPostResponse(BaseModel):
    pass


class V1SalesInvoicesBatchPutResponse(BaseModel):
    pass


class V1SalesInvoicesCreateSaleInvoiceWithGeneratingReferencePostResponse(BaseModel):
    pass


class V1SalesInvoicesIdDeleteResponse(BaseModel):
    pass


class V1SalesInvoicesIdPutResponse(BaseModel):
    pass


class V1SalesRepsPostResponse(BaseModel):
    pass


class V1SalesRepsBatchPutResponse(BaseModel):
    pass


class V1SalesRepsIdDeleteResponse(BaseModel):
    pass


class V1SalesRepsIdPutResponse(BaseModel):
    pass


class V1SuppliersPostResponse(BaseModel):
    pass


class V1SuppliersBatchPutResponse(BaseModel):
    pass


class V1SuppliersIdDeleteResponse(BaseModel):
    pass


class V1SuppliersIdPutResponse(BaseModel):
    pass


class V1SuppliersItemIdAccountTransGetResponse(RootModel[List[AccountTranDto]]):
    root: List[AccountTranDto]


class V1VatCategoriesVatRatesPostRequest(RootModel[List[VatRatesByVatCategoryDto]]):
    root: List[VatRatesByVatCategoryDto]


class V1VatCategoriesVatRatesPostResponse(BaseModel):
    pass


class BatchItemCashPaymentDto(BaseModel):
    item: Optional[CashPaymentDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class BatchItemPaymentDto(BaseModel):
    item: Optional[PaymentDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class BatchItemProductDto(BaseModel):
    item: Optional[ProductDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class BatchItemSaleRepsDto(BaseModel):
    item: Optional[SaleRepsDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class BatchItemSalesInvoiceCreditNoteDto(BaseModel):
    item: Optional[SalesInvoiceCreditNoteDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class CashReceiptDto(BaseModel):
    acCode: Optional[str] = None
    acEntries: Optional[List[AcEntryDto]] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    customerId: Optional[int] = None
    detailCollection: Optional[List[str]] = None
    discount: Optional[float] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    ledger: Optional[float] = None
    note: Optional[str] = None
    plaidTransactionId: Optional[str] = None
    procDate: Optional[datetime] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    unallocated: Optional[float] = None
    vatEntries: Optional[List[VatEntryDto]] = None
    vatTypeId: Optional[int] = None


class CashReceiptQueryDto(BaseModel):
    acCode: Optional[str] = None
    acEntries: Optional[List[AcEntryDto]] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    customerId: Optional[int] = None
    detailCollection: Optional[List[str]] = None
    discount: Optional[float] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    ledger: Optional[float] = None
    note: Optional[str] = None
    plaidTransactionId: Optional[str] = None
    procDate: Optional[datetime] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    unallocated: Optional[float] = None
    vatEntries: Optional[List[VatEntryDto]] = None
    vatTypeId: Optional[int] = None


class CustomerQueryDto(BaseModel):
    accountName: Optional[str] = None
    accountNumber: Optional[str] = None
    additionalEmails: Optional[List[str]] = None
    address: Optional[List[str]] = None
    authCode: Optional[str] = None
    bank: Optional[EFTBankDto] = None
    businessIdentifierCode: Optional[str] = None
    code: Optional[str] = None
    contact: Optional[str] = None
    delivery: Optional[List[str]] = None
    eFTReference: Optional[str] = None
    email: Optional[str] = None
    fax: Optional[str] = None
    id: Optional[int] = None
    internationalBankAccountNumber: Optional[str] = None
    mobile: Optional[str] = None
    name: Optional[str] = None
    ourCode: Optional[str] = None
    ownerTypeId: Optional[int] = None
    phone: Optional[str] = None
    timestamp: Optional[str] = None
    vatAnalysisTypeId: Optional[int] = None
    vatReg: Optional[str] = None
    vatType: Optional[int] = None


class FilterClause(BaseModel):
    Expression: Optional[SingleValueNode] = None
    ItemType: Optional[IEdmTypeReference] = None
    RangeVariable_1: Optional[RangeVariable] = Field(None, alias='RangeVariable')


class IEdmModel(BaseModel):
    DirectValueAnnotationsManager: Optional[IEdmDirectValueAnnotationsManager] = None
    ReferencedModels: Optional[List[IEdmModel]] = None
    SchemaElements: Optional[List[IEdmSchemaElement]] = None
    VocabularyAnnotations: Optional[List[IEdmVocabularyAnnotation]] = None


class ODataQueryContext(BaseModel):
    ElementClrType: Optional[str] = None
    ElementType: Optional[IEdmType] = None
    Model: Optional[IEdmModel] = None


class OrderByClause(BaseModel):
    Direction_1: Optional[Direction] = Field(None, alias='Direction')
    Expression: Optional[SingleValueNode] = None
    ItemType: Optional[IEdmTypeReference] = None
    RangeVariable_1: Optional[RangeVariable] = Field(None, alias='RangeVariable')
    ThenBy: Optional[OrderByClause] = None


class OrderByQueryOption(BaseModel):
    Context: Optional[ODataQueryContext] = None
    OrderByClause_1: Optional[OrderByClause] = Field(None, alias='OrderByClause')
    OrderByNodes: Optional[List[OrderByNode]] = None
    RawValue: Optional[str] = None
    Validator: Optional[OrderByQueryValidator] = None


class OwnerOpeningBalanceDto(BaseModel):
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    isChanged: Optional[bool] = None
    procDate: Optional[datetime] = None
    reference: Optional[str] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    totalVAT: Optional[float] = None
    unpaid: Optional[float] = None
    vatEntries: Optional[List[OwnerOpeningBalanceVatEntryDto]] = None


class PageResultCashReceiptQueryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[CashReceiptQueryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultCustomerQueryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[CustomerQueryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultPaymentQueryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[PaymentQueryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultProductDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[ProductDto]] = None
    NextPageLink: Optional[str] = None


class PageResultSaleRepsDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[SaleRepsDto]] = None
    NextPageLink: Optional[str] = None


class PageResultSalesCreditNoteQueryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[SalesCreditNoteQueryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultSalesInvoiceQueryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[SalesInvoiceQueryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultSupplierQueryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[SupplierQueryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultUserDefinedFieldDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[UserDefinedFieldDto]] = None
    NextPageLink: Optional[str] = None


class PageResultVatAnalysisTypeDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[VatAnalysisTypeDto]] = None
    NextPageLink: Optional[str] = None


class PageResultVatCategoryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[VatCategoryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultVatRateDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[VatRateDto]] = None
    NextPageLink: Optional[str] = None


class PageResultVatTypeDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[VatTypeDto]] = None
    NextPageLink: Optional[str] = None


class PurchaseDto(BaseModel):
    acCode: Optional[str] = None
    acEntries: Optional[List[AcEntryDto]] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    detailCollection: Optional[List[str]] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    isDiscrepancyAccepted: Optional[bool] = None
    netGoods: Optional[float] = None
    netServices: Optional[float] = None
    note: Optional[str] = None
    postponedAccounting: Optional[bool] = None
    procDate: Optional[datetime] = None
    reference: Optional[str] = None
    supplierId: Optional[int] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    totalNet: Optional[float] = None
    totalVAT: Optional[float] = None
    unallocated: Optional[float] = None
    unpaid: Optional[float] = None
    vatEntries: Optional[List[VatEntryDto]] = None
    vatTypeId: Optional[int] = None


class PurchaseQueryDto(BaseModel):
    acCode: Optional[str] = None
    acEntries: Optional[List[AcEntryDto]] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    detailCollection: Optional[List[str]] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    netGoods: Optional[float] = None
    netServices: Optional[float] = None
    note: Optional[str] = None
    postponedAccounting: Optional[bool] = None
    procDate: Optional[datetime] = None
    reference: Optional[str] = None
    supplierId: Optional[int] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    totalNet: Optional[float] = None
    totalVAT: Optional[float] = None
    unallocated: Optional[float] = None
    unpaid: Optional[float] = None
    vatEntries: Optional[List[VatEntryDto]] = None
    vatTypeId: Optional[int] = None


class QuoteDto(BaseModel):
    acCode: Optional[str] = None
    closedDate: Optional[datetime] = None
    comments: Optional[str] = None
    companyId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    customerOwnerId: Optional[int] = None
    customerOwnerName: Optional[str] = None
    ddNumber: Optional[str] = None
    deliveryList: Optional[str] = None
    deliveryTo: Optional[List[str]] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    layoutType: Optional[int] = None
    note: Optional[str] = None
    poNumber: Optional[str] = None
    procDate: Optional[datetime] = None
    productTrans: Optional[List[QuoteProductTransDto]] = None
    reference: Optional[str] = None
    saleInvoiceId: Optional[int] = None
    saleRepCode: Optional[str] = None
    saleRepId: Optional[int] = None
    timeStamp: Optional[str] = None
    total: Optional[float] = None
    totalNet: Optional[float] = None
    totalVat: Optional[float] = None
    vatTypeId: Optional[int] = None


class QuoteGeneratingInvoiceDto(BaseModel):
    quoteId: Optional[int] = None
    saleInvoice: Optional[SalesInvoiceCreditNoteDto] = None


class SalesEntryDto(BaseModel):
    acCode: Optional[str] = None
    acEntries: Optional[List[AcEntryDto]] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    customerId: Optional[int] = None
    detailCollection: Optional[List[str]] = None
    details: Optional[str] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    netGoods: Optional[float] = None
    netServices: Optional[float] = None
    note: Optional[str] = None
    procDate: Optional[datetime] = None
    reference: Optional[str] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    totalNet: Optional[float] = None
    totalVAT: Optional[float] = None
    unpaid: Optional[float] = None
    vatEntries: Optional[List[VatEntryDto]] = None
    vatTypeId: Optional[int] = None


class SalesEntryQueryDto(BaseModel):
    acCode: Optional[str] = None
    acEntries: Optional[List[AcEntryDto]] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    customerId: Optional[int] = None
    detailCollection: Optional[List[str]] = None
    details: Optional[str] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    netGoods: Optional[float] = None
    netServices: Optional[float] = None
    note: Optional[str] = None
    procDate: Optional[datetime] = None
    reference: Optional[str] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    totalNet: Optional[float] = None
    totalVAT: Optional[float] = None
    unpaid: Optional[float] = None
    vatEntries: Optional[List[VatEntryDto]] = None
    vatTypeId: Optional[int] = None


class SalesQueryDto(BaseModel):
    acCode: Optional[str] = None
    acEntries: Optional[List[AcEntryDto]] = None
    bookTranTypeId: Optional[int] = None
    customFields: Optional[List[AcudfValueDto]] = None
    customerId: Optional[int] = None
    details: Optional[str] = None
    entryDate: Optional[datetime] = None
    id: Optional[int] = None
    loType: Optional[str] = None
    note: Optional[str] = None
    procDate: Optional[datetime] = None
    reference: Optional[str] = None
    timestamp: Optional[str] = None
    total: Optional[float] = None
    totalNet: Optional[float] = None
    totalVAT: Optional[float] = None
    unpaid: Optional[float] = None
    vatEntries: Optional[List[VatEntryDto]] = None
    vatTypeId: Optional[int] = None


class SelectExpandClause(BaseModel):
    AllSelected: Optional[bool] = None
    SelectedItems: Optional[List[SelectItem]] = None


class SelectExpandQueryOption(BaseModel):
    Context: Optional[ODataQueryContext] = None
    RawExpand: Optional[str] = None
    RawSelect: Optional[str] = None
    SelectExpandClause_1: Optional[SelectExpandClause] = Field(
        None, alias='SelectExpandClause'
    )
    Validator: Optional[SelectExpandQueryValidator] = None


class SkipQueryOption(BaseModel):
    Context: Optional[ODataQueryContext] = None
    RawValue: Optional[str] = None
    Validator: Optional[SkipQueryValidator] = None
    Value: Optional[int] = None


class SupplierDto(BaseModel):
    accountName: Optional[str] = None
    accountNumber: Optional[str] = None
    additionalEmails: Optional[List[str]] = None
    address: Optional[List[str]] = None
    authCode: Optional[str] = None
    bank: Optional[EFTBankDto] = None
    businessIdentifierCode: Optional[str] = None
    code: Optional[str] = None
    contact: Optional[str] = None
    eFTReference: Optional[str] = None
    email: Optional[str] = None
    fax: Optional[str] = None
    id: Optional[int] = None
    internationalBankAccountNumber: Optional[str] = None
    ledgerBalance: Optional[float] = None
    mobile: Optional[str] = None
    name: Optional[str] = None
    openingBalance: Optional[OwnerOpeningBalanceInPeriodsDto] = None
    openingBalances: Optional[List[OwnerOpeningBalanceDto]] = None
    ourCode: Optional[str] = None
    ownerTypeId: Optional[int] = None
    phone: Optional[str] = None
    postponedAccounting: Optional[bool] = None
    timestamp: Optional[str] = None
    vatAnalysisTypeId: Optional[int] = None
    vatReg: Optional[str] = None
    vatType: Optional[int] = None


class TopQueryOption(BaseModel):
    Context: Optional[ODataQueryContext] = None
    RawValue: Optional[str] = None
    Validator: Optional[TopQueryValidator] = None
    Value: Optional[int] = None


class V1CashPaymentsBatchPutRequest(RootModel[List[BatchItemCashPaymentDto]]):
    root: List[BatchItemCashPaymentDto]


class V1CustomersItemIdOpeningBalanceListGetResponse(
    RootModel[List[OwnerOpeningBalanceDto]]
):
    root: List[OwnerOpeningBalanceDto]


class V1CustomersItemIdQuotesGetResponse(RootModel[List[QuoteDto]]):
    root: List[QuoteDto]


class V1PaymentsBatchPutRequest(RootModel[List[BatchItemPaymentDto]]):
    root: List[BatchItemPaymentDto]


class V1ProductsBatchPutRequest(RootModel[List[BatchItemProductDto]]):
    root: List[BatchItemProductDto]


class V1SalesCreditNotesBatchPutRequest(
    RootModel[List[BatchItemSalesInvoiceCreditNoteDto]]
):
    root: List[BatchItemSalesInvoiceCreditNoteDto]


class V1SalesInvoicesBatchPutRequest(
    RootModel[List[BatchItemSalesInvoiceCreditNoteDto]]
):
    root: List[BatchItemSalesInvoiceCreditNoteDto]


class V1SalesRepsBatchPutRequest(RootModel[List[BatchItemSaleRepsDto]]):
    root: List[BatchItemSaleRepsDto]


class V1SuppliersItemIdOpeningBalanceListGetResponse(
    RootModel[List[OwnerOpeningBalanceDto]]
):
    root: List[OwnerOpeningBalanceDto]


class BatchItemCashReceiptDto(BaseModel):
    item: Optional[CashReceiptDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class BatchItemPurchaseDto(BaseModel):
    item: Optional[PurchaseDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class BatchItemQuoteDto(BaseModel):
    item: Optional[QuoteDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class BatchItemSalesEntryDto(BaseModel):
    item: Optional[SalesEntryDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class BatchItemSupplierDto(BaseModel):
    item: Optional[SupplierDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class CustomerDto(BaseModel):
    accountName: Optional[str] = None
    accountNumber: Optional[str] = None
    additionalEmails: Optional[List[str]] = None
    address: Optional[List[str]] = None
    authCode: Optional[str] = None
    bank: Optional[EFTBankDto] = None
    businessIdentifierCode: Optional[str] = None
    code: Optional[str] = None
    contact: Optional[str] = None
    delivery: Optional[List[str]] = None
    eFTReference: Optional[str] = None
    email: Optional[str] = None
    fax: Optional[str] = None
    id: Optional[int] = None
    internationalBankAccountNumber: Optional[str] = None
    ledgerBalance: Optional[float] = None
    mobile: Optional[str] = None
    name: Optional[str] = None
    openingBalance: Optional[OwnerOpeningBalanceInPeriodsDto] = None
    openingBalances: Optional[List[OwnerOpeningBalanceDto]] = None
    ourCode: Optional[str] = None
    ownerTypeId: Optional[int] = None
    phone: Optional[str] = None
    timestamp: Optional[str] = None
    vatAnalysisTypeId: Optional[int] = None
    vatReg: Optional[str] = None
    vatType: Optional[int] = None


class FilterQueryOption(BaseModel):
    Context: Optional[ODataQueryContext] = None
    FilterClause_1: Optional[FilterClause] = Field(None, alias='FilterClause')
    RawValue: Optional[str] = None
    Validator: Optional[FilterQueryValidator] = None


class InlineCountQueryOption(BaseModel):
    Context: Optional[ODataQueryContext] = None
    RawValue: Optional[str] = None
    Value_1: Optional[Value] = Field(None, alias='Value')


class ODataQueryOptionsAccountDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsAnalysisCategoryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsBankAccountQueryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsBookTranTypeDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsCashPaymentQueryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsCashReceiptQueryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsCategoryTypeDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsCompanySettingDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsCustomerQueryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsOwnerTypeDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsOwnerTypeGroupDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsPaymentQueryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsProductDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsPurchaseQueryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsQuoteDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsSaleRepsDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsSalesCreditNoteQueryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsSalesEntryQueryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsSalesInvoiceQueryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsSalesQueryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsSupplierQueryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsUserDefinedFieldDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsVatAnalysisTypeDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsVatCategoryDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsVatRateDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class ODataQueryOptionsVatTypeDto(BaseModel):
    Context: Optional[ODataQueryContext] = None
    Filter: Optional[FilterQueryOption] = None
    IfMatch: Optional[Dict[str, Any]] = None
    IfNoneMatch: Optional[Dict[str, Any]] = None
    InlineCount: Optional[InlineCountQueryOption] = None
    OrderBy: Optional[OrderByQueryOption] = None
    RawValues: Optional[ODataRawQueryOptions] = None
    Request: Optional[Dict[str, Any]] = None
    SelectExpand: Optional[SelectExpandQueryOption] = None
    Skip: Optional[SkipQueryOption] = None
    Top: Optional[TopQueryOption] = None
    Validator: Optional[ODataQueryValidator] = None


class PageResultPurchaseQueryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[PurchaseQueryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultQuoteDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[QuoteDto]] = None
    NextPageLink: Optional[str] = None


class PageResultSalesEntryQueryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[SalesEntryQueryDto]] = None
    NextPageLink: Optional[str] = None


class PageResultSalesQueryDto(BaseModel):
    Count: Optional[int] = None
    Items: Optional[List[SalesQueryDto]] = None
    NextPageLink: Optional[str] = None


class V1CashReceiptsBatchPutRequest(RootModel[List[BatchItemCashReceiptDto]]):
    root: List[BatchItemCashReceiptDto]


class V1PurchasesBatchPutRequest(RootModel[List[BatchItemPurchaseDto]]):
    root: List[BatchItemPurchaseDto]


class V1QuotesBatchPutRequest(RootModel[List[BatchItemQuoteDto]]):
    root: List[BatchItemQuoteDto]


class V1SalesEntriesBatchPutRequest(RootModel[List[BatchItemSalesEntryDto]]):
    root: List[BatchItemSalesEntryDto]


class V1SuppliersBatchPutRequest(RootModel[List[BatchItemSupplierDto]]):
    root: List[BatchItemSupplierDto]


class BatchItemCustomerDto(BaseModel):
    item: Optional[CustomerDto] = None
    opCode: Optional[OpCode] = Field(
        None, description='1 - Create\r\n2 - Update\r\n3 - Delete'
    )


class V1CustomersBatchPutRequest(RootModel[List[BatchItemCustomerDto]]):
    root: List[BatchItemCustomerDto]


IEdmModel.model_rebuild()
OrderByClause.model_rebuild()
